# -*- coding: utf-8 -*-
"""full regression model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GWOv5-2NUvWGhFk60P9kfwRWY1pCFR4K
"""

import numpy as np
import matplotlib.pyplot as plt
x=np.zeros(5)
y=np.zeros(5)
for i in range(5):
  x[i]=int(input('enter size of house in square feet: '))
  y[i]=int(input(f'please enter the price of the {x[i]} square feet house in thousands of dollars '))
print('this is your dataset: ')
for i in range(len(x)):
  print(x[i], ',', y[i])

plt.style.use('seaborn-v0_8-poster')
w=0
b=0

def compute_cost(x,y,w,b):
  totalcost=0
  m=len(x)
  for i in range(m):
    f_wb=(w*x[i])+b
    cost=(f_wb-y[i])**2
    totalcost=totalcost+cost
  totalcost=totalcost/(2*m)
  return totalcost

#compute gradient function to get derivatives now
def compute_gradient(x,y,w,b):
  m=len(x)
  dj_dw=0
  dj_db=0
  for i in range(m):
    f_wb=(w*x[i])+b
    dj_dw_i=(f_wb-y[i])*x[i]
    dj_db_i=(f_wb-y[i])
    dj_dw+=dj_dw_i
    dj_db+=dj_db_i
  dj_dw=dj_dw/m
  dj_db=dj_db/m
  return dj_db, dj_dw

#gradient function now
def gradient_descent(x,y,w,b,alpha,iterations):
  for i in range(iterations):
    dj_db,dj_dw =compute_gradient(x,y,w,b)
    w=w-(alpha*dj_dw)
    b=b-(alpha*dj_db)
  return w,b

#setting the parameters
alpha=0.0001
iterations=100000
w, b=gradient_descent(x,y,w,b,alpha,iterations)
print(f'optimum value for m is {w} and for b its {b}')

#calling compute model function
def compute_model(x,w,b):
  m=len(x)
  f_wb=np.zeros(m)
  for i in range(m):
    f_wb[i]=(w*x[i])+b
  return f_wb

predictedy=compute_model(x,w,b)
plt.scatter(x,y,marker='x',c='r',label='actual points')
plt.plot(x,predictedy,c='b',label='our prediction line')
plt.xlabel('square feet of house')
plt.ylabel('average price of house in $1000s')
plt.legend(loc='upper left')
plt.show()

xbar=int(input('please enter square feet of house you would like to sell: '))
ybar=(w*xbar)+b
print(f'a house of {xbar} square feet will be sold for ${ybar} ')